version: '2'
services:
  api:
    build: .
    container_name: api
    env_file: .env
    environment:
      - DB_HOST=mongodb
      - DOMAIN=http://localhost:8089
    ports:
      - 49100:8089
  webapp:
    build: ../snapHole-webapp
    container_name: webapp
    ports:
      - 3000:3000
